#구문오류
괄괄호 개수를 잘못 입력하는 등의 오류로 코드가 실행조차 되지 않는 오류
#예외 or #런타임오류
문법적 오류를 제외하고 코드 실행 중간에 발생하는 오류
-> 이것을 처리하는 방법 #예외처리 #exception_handling
-> SystaxError() 등등으로 개발자도구에 뜬다

조건문을 사용해서 예외가 발생하지 않게 만드는 것을 #기본예외처리

#고금예외처리 try catch finally
try {
    // 예외가 발생할 가능성이 있는 코드
} catch (exception) {
    // 예외가 발생했을 때 실핼할 코드
}
finally{
    // 무조건 실행할 코드 -> 필요한 경우에만 사용
}

try 구문 안에서 예외를 발생하면 이를 catch구문에서 처리함
finally 구문을 사용하는 이유 
: return이 있을 경우가 있기 때문에..!

#예외객체 (exception object)
#throw
try {
   
} catch (exception) {
    // exception이 예외객체(catch의 괄호에 쓴 것) e라고 쓰기도 함
}
name : 예외 이름 , message : 예외 메시지